age = input("Enter your age:")
x= int(input("Enter your first number:"))
y= int(input("Enter your second number:"))
print("Addition",x+y)
print("Subtraction", x-y)
print("multiplication",x*y)
print("division",x/y)
name= input("Enter your name :")
print("keep going, "+ name +" !")
print("you are ,"+ age +",years old you got time !!")
