name=input("enter your name")
num= int(input("Enter your number:"))
nun=int(input("Enter your number:"))
print("Addition:", num+nun)
print("subtraction:",num-nun)
print("multiplication:",num*nun)
print("division:",num/nun)
print("exponent:",num**nun)
print("squared of num" , num*num)
print("squared of nun:",nun*nun)
print("here are your results ",name,"!!!")
